### PR TITLE
Fix: Minting Message UI #112

### LINKED ISSUE #112: Mobile - Minting Message UI Broken
## Problem
- **URL** : 

**Description**

 On mobile, click Contents -> click NFT -> click Mint Now -> Minting message UI broken

## Steps To Reproduce

- 
- 
- 

**Screenshots**

 

Image

## Environment:

- OS info:         
- Browser platform:    
- Device:

### PR DESCRIPTION
**Pull request by Nathy-bajo**
Resolves #112

This fix ensures that the Minting Message UI is no longer broken and provides a consistent user experience across all screen sizes.

`Screenshot`
418166889-0411e337-8837-4767-9a80-d30c8c213631

## Summary by CodeRabbit

- **Style**
	- Enhanced the layout for improved responsiveness and centralized alignment.
	- Adjusted spacing and text alignment within carousel sections for a consistent appearance.
	- Optimized button sizing for better flexibility across different screens.

### CODE REVIEW

File: packages/main-ui/src/pages/contents/_id/minting_popup.rs [hunk 1]
```diff
@@ -111,15 +110,15 @@ pub fn MintingPopup(lang: Language, id: ReadOnlySignal<i64>) -> Element {
...
+                div { class: "w-full flex flex-col justify-between items-center gap-[20px] pt-[40px] p-4",
                     CompleteIcon { size: 120 }
                     div { class: "flex flex-col w-full items-center justify-center gap-[20px] text-[#5B5B5B]",
 
                         p { class: "w-full text-center text-[15px] tracking-wide text-[#5B5B5B] font-bold",
                             "{tr.complete_text}"
                         }
                         button {
-                            class: "flex justify-center items-center rounded-[12px] w-[440px] h-[50px] font-normal text-[18px] bg-[#24B28C] hover:bg-[#1E9E7A] text-white",
+                            class: "flex justify-center items-center rounded-[12px] w-full max-w-[440px] h-[50px] font-normal text-[18px] bg-[#24B28C] hover:bg-[#1E9E7A] text-white", // Use max-width for responsiveness
```
Comment (hackartists) [inline packages/main-ui/src/pages/contents/_id/minting_popup.rs:121]:
```suggestion
                            class: "flex justify-center items-center rounded-[12px] w-full h-[50px] font-normal text-[18px] bg-[#24B28C] hover:bg-[#1E9E7A] text-white", // Use max-width for responsiveness
```

even if it contains max-w, it would be inherited width of parent maybe.

**Review by hackartists — APPROVED** [review]
LGTM

**Comment by hackartists** [comment]
@Nathy-bajo Next time, plase attach fixed UI .

**Comment by Nathy-bajo** [comment]
> @Nathy-bajo Next time, plase attach fixed UI .

What do you mean please

**Review by hackartists — APPROVED** [review]

**Comment by hackartists** [comment]
> > @Nathy-bajo Next time, plase attach fixed UI .
> 
> What do you mean please

@Nathy-bajo  Currently, you might attach previouse screentshot, right?
I hope you to attach screenshot reflecting fixed code to PR description.

**Comment by Nathy-bajo** [comment]
> > > @Nathy-bajo Next time, plase attach fixed UI .
> > 
> > 
> > What do you mean please
> 
> @Nathy-bajo Currently, you might attach previouse screentshot, right? I hope you to attach screenshot reflecting fixed code to PR description.

Yes, I will be doing that once I'm more familiar with `dev.incheonheroes.world`
