### PR TITLE
fix: make profile page tables responsive on mobile devices #109

### LINKED ISSUE #109: My profile page Ui broken on mobile
## Problem
- **URL** : https://incheonheroes.world/ko/my-profile

**Description**

Table UIs are broken.

## Steps To Reproduce

- login
- go to my profile by clicking profile image
- 

**Screenshots**

## Environment:

- OS info:        Android 
- Browser platform:  Chrome   
- Device:   Gallaxy fold

### PR DESCRIPTION
**Pull request by Nathy-bajo**
Resolves #109

Improved table layouts and styling for better mobile responsiveness and user experience in various history components.

Screenshots
418077906-8f1d3571-98a3-4733-a4e0-e1d03d7aa44d

## Summary by CodeRabbit

- **Chores**
	- Upgraded a key dependency to enhance toolset reliability.
  
- **Style**
	- Refined the layout and responsiveness of profile page components, improving horizontal scrolling and adapting views for better performance on various screen sizes.

### CODE REVIEW

**Comment by hackartists** [comment]
@Nathy-bajo could you attach capture image for this work?

**Comment by Nathy-bajo** [comment]
> @Nathy-bajo could you attach capture image for this work?

Do you mean the screenshot from the issue?

File: packages/main-ui/src/pages/my_profile/page.rs [hunk 1]
```diff
@@ -132,27 +132,28 @@ pub fn MissionHistoryComponent(lang: Language, histories: Vec<MissionHistory>) -
...
+
     rsx! {
         div {
-            class: "flex flex-col justify-start items-start bg-transparent border border-[#e0e0e0] rounded-[12px]",
-            style: if responsive.width() > 1200.0 { "width: 100%;" } else { "width: 110px; height: 100%" },
-            div { class: if responsive.width() > 1200.0 { "flex flex-row w-full h-[45px] justify-start items-start font-semibold text-[16px] text-[#636363] border-b border-b-[#e0e0e0]" } else { "flex flex-col h-full justify-start items-start font-semibold text-[14px] text-[#636363] border-b border-b-[#e0e0e0]" },
-                div { class: "flex flex-1 justify-start items-center px-[20px] py-[10px]",
+            class: "flex flex-col justify-start items-start bg-transparent border border-[#e0e0e0] rounded-[12px] overflow-x-auto",
+            style: if responsive.width() > 1200.0 { "width: 100%;" } else { "width: 100%; min-width: 300px;" },
+            div { class: "flex flex-row w-full h-[45px] justify-start items-start font-semibold text-[16px] text-[#636363] border-b border-b-[#e0e0e0]",
```
Comment (hackartists) [inline packages/main-ui/src/pages/my_profile/page.rs:140]:
```suggestion
            class: "flex flex-col justify-start items-start bg-transparent border border-[#e0e0e0] rounded-[12px] overflow-x-auto",
            div {
                  class: "w-full min-w-[300px]" ,
                      div { class: "flex flex-row w-full h-[45px] justify-start items-start font-semibold text-[16px] text-[#636363] border-b border-b-[#e0e0e0]",
                      .....
               }
```

At this, you may not need to use style. it can complete by tailwindcss. 
And I think `overflow-x-scoll` may wrap a `div` wrapping table.

@Nathy-bajo check it out and attach sccrennshot

**Review by hackartists — APPROVED** [review]
Review comment then you can merged yourself.
Because it seems not to be critical comment even if you do not reflect the comment.

So I approved.

File: packages/main-ui/src/pages/my_profile/page.rs (hunk 1 above)
Comment (Nathy-bajo) [reply packages/main-ui/src/pages/my_profile/page.rs:140]: @hackartists Yes, after reviewing it again, using TailwindCSS for responsiveness and avoiding inline styles makes the code more consistent and maintainable.

Thank you for the suggestion!
